### ISSUE TITLE
ClassCastException on ErlElementPositionSorter

### ISSUE THREAD

**Issue by jesperes** [erlang/erlide_eclipse#319]
When attempting to expand Erlang modules in the project explorer, I get:

```!ENTRY org.eclipse.ui.navigator 4 0 2018-06-04 14:12:48.524
!MESSAGE org.erlide.ui.navigator.ErlElementPositionSorter cannot be cast to org.eclipse.jface.viewers.ViewerSorter: An exception occurred invoking extension: org.erlide.ui.navigator.ErlElementPositionSorterId: commonSorter for object null
!STACK 0
java.lang.ClassCastException: org.erlide.ui.navigator.ErlElementPositionSorter cannot be cast to org.eclipse.jface.viewers.ViewerSorter
	at org.eclipse.ui.internal.navigator.sorters.CommonSorterDescriptor$1.run(CommonSorterDescriptor.java:97)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.navigator.sorters.CommonSorterDescriptor.createSorter(CommonSorterDescriptor.java:94)
	at org.eclipse.ui.internal.navigator.sorters.NavigatorSorterService.getSorter(NavigatorSorterService.java:84)
	at org.eclipse.ui.internal.navigator.sorters.NavigatorSorterService.findSorter(NavigatorSorterService.java:115)
	at org.eclipse.ui.navigator.CommonViewerSorter.compare(CommonViewerSorter.java:108)
	at org.eclipse.jface.viewers.TreePathViewerSorter.lambda$0(TreePathViewerSorter.java:102)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1438)
```

This seems to be caused by `ErlElementPositionSorter` not being a `ViewerSorter` as the extension point requires. Instead it is a `ViewerComparator`.

**Comment by vladdu** [comment]
Thanks! I will check it out in more detail, but the ViewerSorter documentation says "It is recommended to use ViewerComparator instead."

**Comment by vladdu** [comment]
It's probably just a matter of replacing the parent class. I wonder why it has been working before... What version of Eclipse do you use?

**Comment by jesperes** [comment]
Oxygen, but I'm using `org.erlide.target.target` which is pointing to Neon.

**Comment by jesperes** [comment]
I had to leave work early today, but I might have a PR for you later tonight. :D

**Comment by jesperes** [comment]
It probably hasn't worked before, but the exception goes unnoticed unless you look at stdout.

**Comment by jesperes** [comment]
You beat me to it. :)
